buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    // Enable R8 Full Mode for aggressive tree-shaking and optimization
    project.ext.set("android.enableR8.fullMode", "true")
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
