services:
  - type: web
    name: saraa-services
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: RENDER
        value: "true"
      - key: SESSION_SECRET
        generateValue: true
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: anwer1230/Abu_Mlk
      - key: GITHUB_BRANCH
        value: main
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_B64
        sync: false
