const fs = require('fs');
const path = require('path');

const CSV_FILE = path.join(__dirname, 'in/settings-links.csv');
const OUT_FILE = path.join(__dirname, '../lib/settingsSearch/generated.ts');

function generate() {
  const sections = ['General', 'Privacy', 'Notifications', 'Data', 'Chat', 'Language', 'Folders', 'Devices', 'Stories'];
  let entries = [];

  if (fs.existsSync(CSV_FILE)) {
    const lines = fs.readFileSync(CSV_FILE, 'utf-8').split('\n').filter(Boolean).slice(1);
    entries = lines.map(line => {
      const [id, title, section, url] = line.split(',');
      return { id: (id || '').trim(), title: (title || '').trim(), section: (section || '').trim(), url: (url || '').trim() };
    });
  }

  const outDir = path.dirname(OUT_FILE);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const content = `/**
 * Auto-generated by generate_settings_search.cjs
 * Do not edit manually.
 */

export interface SettingsSearchEntry {
  id: string;
  title: string;
  section: string;
  url: string;
}

export const SETTINGS_SEARCH_SECTIONS = ${JSON.stringify(sections, null, 2)} as const;

export const SETTINGS_SEARCH_ENTRIES: SettingsSearchEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  let changed = true;
  if (fs.existsSync(OUT_FILE)) {
    const existing = fs.readFileSync(OUT_FILE, 'utf-8');
    if (existing === content) {
      changed = false;
    }
  }

  if (changed) {
    fs.writeFileSync(OUT_FILE, content, 'utf-8');
  }

  return { sections, entries, changed };
}

module.exports = {
  OUT_FILE,
  generate,
};
