import { TelegramChat, TelegramMessage, TelegramUser } from '../types';

export const CURRENT_DEMO_USER: TelegramUser = {
  id: 'me',
  firstName: 'مستخدم',
  lastName: 'تليجرام',
  username: 'tg_user',
  phone: '+966500000000',
  bio: 'مطور واجهات Telegram Web الرسمية 🚀',
  isVerified: true,
  isPremium: true,
  status: 'online',
};

export const INITIAL_CHATS: TelegramChat[] = [
  {
    id: 'saved_messages',
    title: 'الرسائل المحفوظة',
    type: 'saved',
    avatarColor: '#3390ec',
    unreadCount: 0,
    isPinned: true,
    lastMessage: {
      text: 'مرحباً بك في سحابة التخزين الشخصية لتليجرام! يمكنك إرسال النصوص والملاحظات والوسائط للوصول إليها من أي جهاز.',
      timestamp: Date.now() - 3600000 * 2,
      isOut: true,
    },
  },
  {
    id: 'service_notifications',
    title: 'Telegram Notifications',
    username: 'telegram',
    type: 'channel',
    avatarColor: '#2b5278',
    unreadCount: 1,
    isPinned: true,
    isVerified: true,
    lastMessage: {
      text: 'تسجيل دخول جديد لحساب تليجرام ويب عبر بروتوكول MTProto v2.0 المشفر بنجاح.',
      timestamp: Date.now() - 1800000,
      isOut: false,
    },
  },
  {
    id: 'group_supergroup_devs',
    title: 'مجتمع مطوري تيليجرام (Supergroup)',
    username: 'tg_dev_community',
    type: 'supergroup',
    avatarColor: '#10b981',
    unreadCount: 3,
    membersCount: 4850,
    isForum: true,
    topics: [
      {
        id: 1,
        title: 'النقاش العام (General)',
        iconColor: 0x3390ec,
        unreadCount: 1,
        isGeneral: true,
      },
      {
        id: 2,
        title: 'مكتبة MTProto والتشفير 🔐',
        iconColor: 0x10b981,
        unreadCount: 2,
      },
      {
        id: 3,
        title: 'تطبيقات الويب المصغرة Mini Apps 📱',
        iconColor: 0xf59e0b,
        unreadCount: 0,
      },
      {
        id: 4,
        title: 'نجوم تليجرام Telegram Stars ⭐',
        iconColor: 0x8b5cf6,
        unreadCount: 0,
      },
    ],
    lastMessage: {
      text: 'تم تفعيل منتديات المواضيع الفائقة (Forum Topics) والتفاعلات الحركية رسمياً! 🚀',
      timestamp: Date.now() - 900000,
      senderName: 'فهد المهندس',
      isOut: false,
    },
  },
  {
    id: 'bot_ai_assistant',
    title: 'المساعد الذكي (Telegram Bot)',
    username: 'smart_helper_bot',
    type: 'bot',
    avatarColor: '#8b5cf6',
    unreadCount: 0,
    isBot: true,
    isVerified: true,
    botInfo: {
      description: 'أنا بوت تليجرام رسمي ذكي مدعوم بتقنيات MTProto وتطبيقات الويب المصغرة (Mini Apps).',
      about: 'مساعد ذكي للردود الآلية وجدولة الرسائل والخدمات التفاعلية.',
    },
    lastMessage: {
      text: '🤖 مرحباً بك في منصة بوتات تليجرام! اضغط /start لبدء استكشاف الأوامر والتطبيقات المصغرة.',
      timestamp: Date.now() - 7200000,
      isOut: false,
    },
  },
  {
    id: 'bot_botfather',
    title: 'BotFather',
    username: 'botfather',
    type: 'bot',
    avatarColor: '#00a884',
    unreadCount: 0,
    isBot: true,
    isVerified: true,
    lastMessage: {
      text: 'I can help you create and manage Telegram bots. Please choose an action: /newbot or /mybots',
      timestamp: Date.now() - 14400000,
      isOut: false,
    },
  },
  {
    id: 'bot_wallet',
    title: 'Telegram Wallet',
    username: 'wallet',
    type: 'bot',
    avatarColor: '#0ea5e9',
    unreadCount: 0,
    isBot: true,
    isVerified: true,
    lastMessage: {
      text: '💳 محفظة تليجرام المدمجة (TON Blockchain). رصيدك الحالي: 145.50 TON.',
      timestamp: Date.now() - 28800000,
      isOut: false,
    },
  },
  {
    id: 'chat_ahmed',
    title: 'أحمد المنصور',
    username: 'ahmed_mansour',
    type: 'private',
    avatarColor: '#ec4899',
    unreadCount: 0,
    isOnline: true,
    lastMessage: {
      text: 'ممتاز جداً! التصميم مطابق لتليجرام الأصلي وسرعة الاستجابة خرافية 👍',
      timestamp: Date.now() - 600000,
      isOut: false,
    },
  },
  {
    id: 'channel_durov',
    title: 'Durov\'s Channel',
    username: 'durov',
    type: 'channel',
    avatarColor: '#0284c7',
    unreadCount: 0,
    isVerified: true,
    membersCount: 2450000,
    lastMessage: {
      text: 'Telegram now has over 950 million active users. Thank you for your support!',
      timestamp: Date.now() - 86400000,
      isOut: false,
    },
  },
];

export const INITIAL_MESSAGES: Record<string, TelegramMessage[]> = {
  saved_messages: [
    {
      id: 'sm_1',
      chatId: 'saved_messages',
      senderId: 'me',
      senderName: 'أنا',
      text: '📌 مرحباً بك في مساحتك الخاصة السحابية على تليجرام.\n\nتستطيع حفظ:\n• الروابط والنصوص المهمة\n• الرسائل الصوتية والملفات\n• الصور ومقاطع الفيديو بجودتها الأصلية',
      timestamp: Date.now() - 3600000 * 5,
      isOut: true,
      status: 'read',
    },
    {
      id: 'sm_2',
      chatId: 'saved_messages',
      senderId: 'me',
      senderName: 'أنا',
      text: 'جرب الميزات الجديدة:\n1. النصوص المنسقة (غامق **bold** ومائل *italic* وكود `monospace`)\n2. النصوص المحجوبة ||Spoiler Text||\n3. الاقتباسات المنسدلة > هذا اقتباس تليجرام رسمي',
      timestamp: Date.now() - 3600000 * 2,
      isOut: true,
      status: 'read',
    },
  ],
  service_notifications: [
    {
      id: 'notif_1',
      chatId: 'service_notifications',
      senderId: 'telegram',
      senderName: 'Telegram',
      text: '🔒 **تأكيد جلسة جديدة:**\n\nتم الاتصال بحسابك بنجاح من متصفح Telegram Web K.\n\n• خادم MTProto: متصل وآمن\n• بروتوكول التشفير: AES-256-IGE & RSA 2048\n• موقع الجلسة: مصدق بالكامل',
      timestamp: Date.now() - 1800000,
      isOut: false,
      status: 'read',
    },
  ],
  group_supergroup_devs: [
    {
      id: 'grp_1',
      chatId: 'group_supergroup_devs',
      senderId: 'user_sara',
      senderName: 'سارة خالد',
      text: 'أهلاً بالجميع في المجموعة الخارقة! 🌟 يمكنكم الآن تصفح المواضيع الفرعية (Forum Topics) عبر التبويبات بالأعلى.',
      timestamp: Date.now() - 1800000,
      isOut: false,
      status: 'read',
      topicId: 1,
      reactions: [
        { emoji: '🔥', count: 6, userReacted: true },
        { emoji: '👍', count: 12, userReacted: false },
      ],
    },
    {
      id: 'grp_2',
      chatId: 'group_supergroup_devs',
      senderId: 'user_fahad',
      senderName: 'فهد المهندس',
      text: 'تم تفعيل منتديات المواضيع الفائقة (Forum Topics) والتفاعلات الحركية رسمياً! 🚀',
      timestamp: Date.now() - 900000,
      isOut: false,
      status: 'read',
      topicId: 2,
      reactions: [
        { emoji: '🚀', count: 8, userReacted: true },
        { emoji: '⭐', count: 5, userReacted: false },
      ],
    },
  ],
  bot_ai_assistant: [
    {
      id: 'bot_msg_1',
      chatId: 'bot_ai_assistant',
      senderId: 'smart_helper_bot',
      senderName: 'المساعد الذكي',
      text: '🤖 مرحباً بك في منصة بوتات تليجرام الرسمية!\n\nاختر أحد الأوامر التالية أو اكتب استفسارك مباشرة:',
      timestamp: Date.now() - 7200000,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [
            { text: '🚀 تشغيل تطبيق مصغر (Mini App)', webApp: { url: 'https://wallet.tg' } },
          ],
          [
            { text: '⚙️ الإعدادات', callbackData: 'bot_settings' },
            { text: '📊 الإحصائيات', callbackData: 'bot_stats' },
          ],
          [
            { text: '⌨️ تفعيل لوحة المفاتيح التفاعلية', callbackData: 'show_keyboard' },
          ],
        ],
      },
    },
  ],
  bot_botfather: [
    {
      id: 'bf_msg_1',
      chatId: 'bot_botfather',
      senderId: 'botfather',
      senderName: 'BotFather',
      text: 'I can help you create and manage Telegram bots. If you\'re new to the Bot API, please see the manual: https://core.telegram.org/bots\n\nYou can control me by sending these commands:\n\n/newbot - create a new bot\n/mybots - edit your bots\n/setname - change bot name\n/setdescription - change bot description',
      timestamp: Date.now() - 14400000,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [{ text: '➕ New Bot (/newbot)', callbackData: 'bf_newbot' }, { text: '🤖 My Bots (/mybots)', callbackData: 'bf_mybots' }],
        ],
      },
    },
  ],
  bot_wallet: [
    {
      id: 'wallet_msg_1',
      chatId: 'bot_wallet',
      senderId: 'wallet',
      senderName: 'Telegram Wallet',
      text: '💳 **محفظة تليجرام**\n\nالرصيد المحدث:\n🔹 145.50 TON (~$800.25 USD)\n\nاختر العملية المطلوبة:',
      timestamp: Date.now() - 28800000,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [{ text: '⚡ فتح المحفظة المصغرة', webApp: { url: 'https://wallet.tg' } }],
          [{ text: '📥 إيداع TON', callbackData: 'wallet_deposit' }, { text: '📤 إرسال أموال', callbackData: 'wallet_send' }],
        ],
      },
    },
  ],
  chat_ahmed: [
    {
      id: 'ahmed_1',
      chatId: 'chat_ahmed',
      senderId: 'me',
      senderName: 'أنا',
      text: 'السلام عليكم أحمد، كيف ترى أداء واجهة تليجرام الجديدة؟',
      timestamp: Date.now() - 1200000,
      isOut: true,
      status: 'read',
    },
    {
      id: 'ahmed_2',
      chatId: 'chat_ahmed',
      senderId: 'ahmed_mansour',
      senderName: 'أحمد المنصور',
      text: 'وعليكم السلام! ممتاز جداً! التصميم مطابق لتليجرام الأصلي وسرعة الاستجابة خرافية 👍',
      timestamp: Date.now() - 600000,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '🔥', count: 1, userReacted: true }],
    },
  ],
  channel_durov: [
    {
      id: 'durov_1',
      chatId: 'channel_durov',
      senderId: 'durov',
      senderName: 'Pavel Durov',
      text: 'Telegram now has over 950 million active users. Thank you for your support and staying with the most private, fast, and free messaging platform on Earth! 🌐',
      timestamp: Date.now() - 86400000,
      isOut: false,
      status: 'read',
      reactions: [
        { emoji: '❤️', count: 14200, userReacted: true },
        { emoji: '🎉', count: 9800, userReacted: false },
        { emoji: '🚀', count: 8300, userReacted: false },
      ],
    },
  ],
};
