import { TelegramChat, TelegramMessage, TelegramUser } from '../types';

export const CURRENT_DEMO_USER: TelegramUser = {
  id: 'user_me',
  firstName: 'المستخدم',
  lastName: 'التليجرامي',
  username: 'telegram_user',
  phone: '+966 50 123 4567',
  photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  bio: 'مرحباً! أستخدم تليجرام ويب للتواصل والعمل.',
  status: 'online',
};

export const INITIAL_CHATS: TelegramChat[] = [
  {
    id: 'saved_messages',
    title: 'الرسائل المحفوظة',
    type: 'saved',
    avatarColor: '#3390ec',
    unreadCount: 0,
    isPinned: true,
    description: 'مساحتك السحابية الخاصة لتخزين الروابط والملاحظات والملفات.',
    lastMessage: {
      text: 'رابط وثائق تيليجرام API الرسمية: https://core.telegram.org/api',
      timestamp: Date.now() - 1000 * 60 * 15,
      isOut: true,
    },
  },
  {
    id: 'channel_tech_arabic',
    title: 'أخبار التقنية والذكاء الاصطناعي 🚀',
    username: 'arabic_tech_news',
    type: 'channel',
    avatarUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#2b5278',
    unreadCount: 3,
    isPinned: true,
    membersCount: 48920,
    description: 'القناة الرسمية لأحدث أخبار التقنية والبرمجة والذكاء الاصطناعي بالعربية.',
    lastMessage: {
      text: 'تحديث جديد لواجهة تليجرام مع تحسينات أداء وسرعة التحميل!',
      timestamp: Date.now() - 1000 * 60 * 45,
      senderName: 'أخبار التقنية',
    },
  },
  {
    id: 'chat_ahmed',
    title: 'أحمد المنصور',
    username: 'ahmed_mansour',
    type: 'private',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#4fae4e',
    unreadCount: 1,
    isOnline: true,
    description: 'مهندس برمجيات | مطور ويب',
    lastMessage: {
      text: 'السلام عليكم، هل جربت الواجهة الجديدة لتليجرام ويب؟',
      timestamp: Date.now() - 1000 * 60 * 5,
      isOut: false,
    },
  },
  {
    id: 'group_developers',
    title: 'ملتقى مطوري الويب والأنظمة 💻',
    username: 'devs_community',
    type: 'supergroup',
    avatarUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#e07a5f',
    unreadCount: 12,
    membersCount: 1420,
    description: 'مجموعة نقاشات برمجية وتقنية وتبادل خبرات التطوير.',
    lastMessage: {
      text: 'سارة: تم إطلاق التحديث مع دعم كامل لبروتوكول MTProto!',
      timestamp: Date.now() - 1000 * 60 * 80,
      senderName: 'سارة خالد',
    },
  },
  {
    id: 'bot_ai_assistant',
    title: 'بوت المساعد الذكي 🤖',
    username: 'smart_helper_bot',
    type: 'bot',
    avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#9b5de5',
    unreadCount: 0,
    description: 'مساعد آلي للترجمة والتلخيص والإجابة الفورية.',
    lastMessage: {
      text: 'أهلاً بك! يمكنك إرسال أي سؤال أو استفسار وسأجيبك فوراً.',
      timestamp: Date.now() - 1000 * 60 * 180,
      senderName: 'المساعد الذكي',
    },
  },
  {
    id: 'channel_telegram_tips',
    title: 'نصائح وحيل تليجرام 💡',
    username: 'telegram_tips_ar',
    type: 'channel',
    avatarUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#00b4d8',
    unreadCount: 0,
    membersCount: 23100,
    description: 'دليلك الشامل لاحتراف ميزات وخفايا تطبيق تليجرام.',
    lastMessage: {
      text: 'هل تعلم أنه يمكنك تنظيم المحادثات في مجلدات مخصصة لتسهيل الوصول؟',
      timestamp: Date.now() - 1000 * 60 * 360,
      senderName: 'نصائح تليجرام',
    },
  },
];

export const INITIAL_MESSAGES: Record<string, TelegramMessage[]> = {
  saved_messages: [
    {
      id: 'sm_1',
      chatId: 'saved_messages',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'ملاحظة: تليجرام ويب يدعم بروتوكول MTProto الرسمي مع مفاتيح API_ID و API_HASH الثابتة.',
      timestamp: Date.now() - 1000 * 60 * 60 * 3,
      isOut: true,
      status: 'read',
      reactions: [{ emoji: '📌', count: 1, userReacted: true }],
    },
    {
      id: 'sm_2',
      chatId: 'saved_messages',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'رابط وثائق تيليجرام API الرسمية: https://core.telegram.org/api',
      timestamp: Date.now() - 1000 * 60 * 15,
      isOut: true,
      status: 'read',
    },
  ],
  chat_ahmed: [
    {
      id: 'msg_a1',
      chatId: 'chat_ahmed',
      senderId: 'ahmed_mansour',
      senderName: 'أحمد المنصور',
      text: 'أهلاً يا صديقي، كيف حالك اليوم؟',
      timestamp: Date.now() - 1000 * 60 * 25,
      isOut: false,
      status: 'read',
    },
    {
      id: 'msg_a2',
      chatId: 'chat_ahmed',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'الحمد لله بخير! أعمل الآن على تطبيق تليجرام ويب مع واجهة مطابقة للأصل تماماً.',
      timestamp: Date.now() - 1000 * 60 * 20,
      isOut: true,
      status: 'read',
      reactions: [{ emoji: '👍', count: 1, userReacted: false }],
    },
    {
      id: 'msg_a3',
      chatId: 'chat_ahmed',
      senderId: 'ahmed_mansour',
      senderName: 'أحمد المنصور',
      text: 'السلام عليكم، هل جربت الواجهة الجديدة لتليجرام ويب؟ سريعة جداً ومرتبة!',
      timestamp: Date.now() - 1000 * 60 * 5,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '🔥', count: 2, userReacted: true }],
    },
  ],
  channel_tech_arabic: [
    {
      id: 'msg_t1',
      chatId: 'channel_tech_arabic',
      senderId: 'arabic_tech_news',
      senderName: 'أخبار التقنية',
      text: '📢 إعلان رسمي من تيليجرام: وصول ميزات جديدة لعملاء الويب وتحديث واجهة المستخدم.',
      timestamp: Date.now() - 1000 * 60 * 120,
      isOut: false,
      status: 'read',
      reactions: [
        { emoji: '🔥', count: 142, userReacted: true },
        { emoji: '❤️', count: 98, userReacted: false },
        { emoji: '👏', count: 45, userReacted: false },
      ],
    },
    {
      id: 'msg_t2',
      chatId: 'channel_tech_arabic',
      senderId: 'arabic_tech_news',
      senderName: 'أخبار التقنية',
      text: 'تحديث جديد لواجهة تليجرام مع تحسينات أداء وسرعة التحميل ودعم كامل للغة العربية والوضع الليلي المريح للعين.',
      timestamp: Date.now() - 1000 * 60 * 45,
      isOut: false,
      status: 'read',
      media: {
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        title: 'تليجرام ويب بالتصميم العصري',
      },
      reactions: [
        { emoji: '🎉', count: 64, userReacted: false },
        { emoji: '👍', count: 110, userReacted: true },
      ],
    },
  ],
  group_developers: [
    {
      id: 'msg_g1',
      chatId: 'group_developers',
      senderId: 'user_khalid',
      senderName: 'خالد عبدالله',
      text: 'مرحباً بالجميع! من منكم قام بربط Telegram MTProto من قبل؟',
      timestamp: Date.now() - 1000 * 60 * 120,
      isOut: false,
      status: 'read',
    },
    {
      id: 'msg_g2',
      chatId: 'group_developers',
      senderId: 'user_sara',
      senderName: 'سارة خالد',
      text: 'سارة: تم إطلاق التحديث مع دعم كامل لبروتوكول MTProto! الربط أصبح سهلاً ومباشراً.',
      timestamp: Date.now() - 1000 * 60 * 80,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '🚀', count: 5, userReacted: true }],
    },
  ],
  bot_ai_assistant: [
    {
      id: 'msg_b1',
      chatId: 'bot_ai_assistant',
      senderId: 'smart_helper_bot',
      senderName: 'المساعد الذكي',
      text: 'أهلاً بك! يمكنك إرسال أي سؤال أو استفسار وسأجيبك فوراً. جرب أن تسألني عن ميزات تليجرام أو تطلب ترجمة.',
      timestamp: Date.now() - 1000 * 60 * 180,
      isOut: false,
      status: 'read',
    },
  ],
  channel_telegram_tips: [
    {
      id: 'msg_tip1',
      chatId: 'channel_telegram_tips',
      senderId: 'telegram_tips_ar',
      senderName: 'نصائح تليجرام',
      text: '💡 نصيحة اليوم:\nيمكنك تثبيت المحادثات المهمة في الأعلى بالضغط المطول واختيار "تثبيت" (Pin) لسهولة الوصول إليها دائماً.',
      timestamp: Date.now() - 1000 * 60 * 360,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '💡', count: 32, userReacted: true }],
    },
  ],
};
