import { TelegramChat, TelegramMessage, TelegramUser } from '../types';

export const CURRENT_DEMO_USER: TelegramUser = {
  id: 'user_me',
  firstName: 'المستخدم',
  lastName: 'التليجرامي',
  username: 'telegram_user',
  phone: '+966 50 123 4567',
  photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  bio: 'مرحباً! أستخدم تليجرام ويب للتواصل والعمل.',
  status: 'online',
};

export const INITIAL_CHATS: TelegramChat[] = [
  {
    id: 'saved_messages',
    title: 'الرسائل المحفوظة',
    type: 'saved',
    avatarColor: '#3390ec',
    unreadCount: 0,
    isPinned: true,
    description: 'مساحتك السحابية الخاصة لتخزين الروابط والملاحظات والملفات.',
    lastMessage: {
      text: 'رابط وثائق تيليجرام API الرسمية: https://core.telegram.org/api',
      timestamp: Date.now() - 1000 * 60 * 15,
      isOut: true,
    },
  },
  {
    id: 'channel_tech_arabic',
    title: 'أخبار التقنية والذكاء الاصطناعي 🚀',
    username: 'arabic_tech_news',
    type: 'channel',
    avatarUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#2b5278',
    unreadCount: 3,
    isPinned: true,
    membersCount: 48920,
    description: 'القناة الرسمية لأحدث أخبار التقنية والبرمجة والذكاء الاصطناعي بالعربية.',
    lastMessage: {
      text: 'تحديث جديد لواجهة تليجرام مع تحسينات أداء وسرعة التحميل!',
      timestamp: Date.now() - 1000 * 60 * 45,
      senderName: 'أخبار التقنية',
    },
  },
  {
    id: 'chat_ahmed',
    title: 'أحمد المنصور',
    username: 'ahmed_mansour',
    type: 'private',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#4fae4e',
    unreadCount: 1,
    isOnline: true,
    description: 'مهندس برمجيات | مطور ويب',
    lastMessage: {
      text: 'السلام عليكم، هل جربت الواجهة الجديدة لتليجرام ويب؟',
      timestamp: Date.now() - 1000 * 60 * 5,
      isOut: false,
    },
  },
  {
    id: 'group_developers',
    title: 'ملتقى مطوري الويب والأنظمة 💻',
    username: 'devs_community',
    type: 'supergroup',
    avatarUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#e07a5f',
    unreadCount: 12,
    membersCount: 1420,
    description: 'مجموعة نقاشات برمجية وتقنية وتبادل خبرات التطوير.',
    inviteLink: 'https://t.me/+join_devs_community_official',
    members: [
      { id: 'm_owner', name: 'خالد عبدالله (المنشئ)', role: 'owner', isOnline: true, avatarColor: '#e17076' },
      { id: 'm_admin1', name: 'سارة خالد', role: 'admin', isOnline: true, avatarColor: '#65aadd' },
      { id: 'm_admin2', name: 'فهد المهندس', role: 'admin', isOnline: false, avatarColor: '#7bc862' },
      { id: 'm_user1', name: 'عمر القحطاني', role: 'member', isOnline: true, avatarColor: '#faa774' },
      { id: 'm_user2', name: 'نورة السالم', role: 'member', isOnline: false, avatarColor: '#ee7aae' },
      { id: 'm_user3', name: 'طارق زياد', role: 'member', isOnline: true, avatarColor: '#a695e7' },
    ],
    lastMessage: {
      text: 'سارة: تم إطلاق التحديث مع دعم كامل لبروتوكول MTProto!',
      timestamp: Date.now() - 1000 * 60 * 80,
      senderName: 'سارة خالد',
    },
  },
  {
    id: 'bot_ai_assistant',
    title: 'المساعد الذكي 🤖',
    username: 'smart_helper_bot',
    type: 'bot',
    isBot: true,
    avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#9b5de5',
    unreadCount: 1,
    description: 'مساعد ذكي تفاعلي متكامل يدعم أزرار الـ Inline، تطبيقات الويب المصغرة Mini Apps، وقوائم الأوامر السريعة.',
    botInfo: {
      description: 'مساعد آلي ذكي متعدد الإمكانيات، يقدم خدمات الترجمة والتلخيص، وإطلاق تطبيقات الويب التفاعلية داخل الدردشة مباشرة.',
      about: 'Telegram Bot Platform Showcase',
      commands: [
        { command: 'start', description: 'تشغيل البوت وبدء المحادثة' },
        { command: 'help', description: 'المساعدة ودليل استخدام البوت' },
        { command: 'app', description: 'فتح تطبيق الويب المصغر (Mini App)' },
        { command: 'keyboard', description: 'إظهار لوحة الأزرار التفاعلية' },
        { command: 'settings', description: 'تخصيص الإعدادات والتفضيلات' },
        { command: 'inline', description: 'دليل الاستعلام الفوري عبر @' },
      ],
      menuButton: {
        type: 'commands',
        text: 'Menu',
      },
    },
    lastMessage: {
      text: 'مرحباً بك! أنا بوت تليجرام التجريبي. جرب الأزرار التفاعلية أدناه:',
      timestamp: Date.now() - 1000 * 60 * 30,
      senderName: 'المساعد الذكي',
    },
  },
  {
    id: 'bot_botfather',
    title: 'BotFather 🤖',
    username: 'BotFather',
    type: 'bot',
    isBot: true,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#2481cc',
    unreadCount: 0,
    description: 'BotFather is the one bot to rule them all. Use it to create new bot accounts and manage your existing bots.',
    botInfo: {
      description: 'BotFather is the official bot used to create and configure Telegram bots.',
      about: 'Official Telegram BotFather',
      commands: [
        { command: 'newbot', description: 'create a new bot' },
        { command: 'mybots', description: 'edit your bots' },
        { command: 'setname', description: "change a bot's name" },
        { command: 'setdescription', description: 'change bot description' },
        { command: 'setcommands', description: 'change the list of commands' },
        { command: 'token', description: 'generate authorization token' },
      ],
      menuButton: {
        type: 'commands',
        text: 'Menu',
      },
    },
    lastMessage: {
      text: 'I can help you create and manage Telegram bots. What would you like to do?',
      timestamp: Date.now() - 1000 * 60 * 120,
      senderName: 'BotFather',
    },
  },
  {
    id: 'bot_wallet',
    title: 'Telegram Wallet 💳',
    username: 'wallet',
    type: 'bot',
    isBot: true,
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#0088cc',
    unreadCount: 0,
    description: 'المحفظة الرسمية لتليجرام: إرسال واستقبال الأصول الرقمية والتطبيقات المالية مباشرة داخل المحادثات.',
    botInfo: {
      description: 'المحفظة المالية الآمنة المدمجة بتليجرام.',
      commands: [
        { command: 'start', description: 'فتح لوحة المحفظة' },
        { command: 'deposit', description: 'شحن الرصيد' },
        { command: 'send', description: 'تحويل الأموال' },
        { command: 'history', description: 'سجل المعاملات' },
      ],
    },
    lastMessage: {
      text: 'رصيدك الحالي: 145.50 TON ($800.25). اضغط لفتح المحفظة المصغرة:',
      timestamp: Date.now() - 1000 * 60 * 240,
      senderName: 'Telegram Wallet',
    },
  },
  {
    id: 'channel_telegram_tips',
    title: 'نصائح وحيل تليجرام 💡',
    username: 'telegram_tips_ar',
    type: 'channel',
    avatarUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=150&auto=format&fit=crop&q=80',
    avatarColor: '#00b4d8',
    unreadCount: 0,
    membersCount: 23100,
    description: 'دليلك الشامل لاحتراف ميزات وخفايا تطبيق تليجرام.',
    lastMessage: {
      text: 'هل تعلم أنه يمكنك تنظيم المحادثات في مجلدات مخصصة لتسهيل الوصول؟',
      timestamp: Date.now() - 1000 * 60 * 360,
      senderName: 'نصائح تليجرام',
    },
  },
];

export const INITIAL_MESSAGES: Record<string, TelegramMessage[]> = {
  saved_messages: [
    {
      id: 'sm_1',
      chatId: 'saved_messages',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'ملاحظة: تليجرام ويب يدعم بروتوكول MTProto الرسمي مع مفاتيح API_ID و API_HASH الثابتة.',
      timestamp: Date.now() - 1000 * 60 * 60 * 3,
      isOut: true,
      status: 'read',
      reactions: [{ emoji: '📌', count: 1, userReacted: true }],
    },
    {
      id: 'sm_2',
      chatId: 'saved_messages',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'رابط وثائق تيليجرام API الرسمية: https://core.telegram.org/api',
      timestamp: Date.now() - 1000 * 60 * 15,
      isOut: true,
      status: 'read',
    },
  ],
  chat_ahmed: [
    {
      id: 'msg_a1',
      chatId: 'chat_ahmed',
      senderId: 'ahmed_mansour',
      senderName: 'أحمد المنصور',
      text: 'أهلاً يا صديقي، كيف حالك اليوم؟',
      timestamp: Date.now() - 1000 * 60 * 25,
      isOut: false,
      status: 'read',
    },
    {
      id: 'msg_a2',
      chatId: 'chat_ahmed',
      senderId: 'user_me',
      senderName: 'أنا',
      text: 'الحمد لله بخير! أعمل الآن على تطبيق تليجرام ويب مع واجهة مطابقة للأصل تماماً.',
      timestamp: Date.now() - 1000 * 60 * 20,
      isOut: true,
      status: 'read',
      reactions: [{ emoji: '👍', count: 1, userReacted: false }],
    },
    {
      id: 'msg_a3',
      chatId: 'chat_ahmed',
      senderId: 'ahmed_mansour',
      senderName: 'أحمد المنصور',
      text: 'السلام عليكم، هل جربت الواجهة الجديدة لتليجرام ويب؟ سريعة جداً ومرتبة!',
      timestamp: Date.now() - 1000 * 60 * 5,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '🔥', count: 2, userReacted: true }],
    },
  ],
  channel_tech_arabic: [
    {
      id: 'msg_t1',
      chatId: 'channel_tech_arabic',
      senderId: 'arabic_tech_news',
      senderName: 'أخبار التقنية',
      text: '📢 إعلان رسمي من تيليجرام: وصول ميزات جديدة لعملاء الويب وتحديث واجهة المستخدم.',
      timestamp: Date.now() - 1000 * 60 * 120,
      isOut: false,
      status: 'read',
      reactions: [
        { emoji: '🔥', count: 142, userReacted: true },
        { emoji: '❤️', count: 98, userReacted: false },
        { emoji: '👏', count: 45, userReacted: false },
      ],
    },
    {
      id: 'msg_t2',
      chatId: 'channel_tech_arabic',
      senderId: 'arabic_tech_news',
      senderName: 'أخبار التقنية',
      text: 'تحديث جديد لواجهة تليجرام مع تحسينات أداء وسرعة التحميل ودعم كامل للغة العربية والوضع الليلي المريح للعين.',
      timestamp: Date.now() - 1000 * 60 * 45,
      isOut: false,
      status: 'read',
      media: {
        type: 'photo',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        title: 'تليجرام ويب بالتصميم العصري',
      },
      reactions: [
        { emoji: '🎉', count: 64, userReacted: false },
        { emoji: '👍', count: 110, userReacted: true },
      ],
    },
  ],
  group_developers: [
    {
      id: 'msg_g1',
      chatId: 'group_developers',
      senderId: 'user_khalid',
      senderName: 'خالد عبدالله',
      text: 'مرحباً بالجميع! من منكم قام بربط Telegram MTProto من قبل؟',
      timestamp: Date.now() - 1000 * 60 * 120,
      isOut: false,
      status: 'read',
    },
    {
      id: 'msg_g2',
      chatId: 'group_developers',
      senderId: 'user_sara',
      senderName: 'سارة خالد',
      text: 'سارة: تم إطلاق التحديث مع دعم كامل لبروتوكول MTProto! الربط أصبح سهلاً ومباشراً.',
      timestamp: Date.now() - 1000 * 60 * 80,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '🚀', count: 5, userReacted: true }],
    },
  ],
  bot_ai_assistant: [
    {
      id: 'msg_b1',
      chatId: 'bot_ai_assistant',
      senderId: 'smart_helper_bot',
      senderName: 'المساعد الذكي',
      text: '🤖 مرحباً بك في منصة بوتات تليجرام المتكاملة (Telegram Web K)!\n\nأنا بوت تجريبي يوضح جميع قدرات البوتات:\n• أزرار الـ Inline التفاعلية\n• تطبيقات الويب المصغرة (Telegram Mini Apps)\n• لوحات الرد السريع والأوامر الفورية\n\nاضغط على أي زر أدناه لتجربة الرد الفوري:',
      timestamp: Date.now() - 1000 * 60 * 30,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [
            {
              text: '🚀 فتح تطبيق الويب (Mini App)',
              webApp: { url: 'https://telegram.org' },
            },
          ],
          [
            {
              text: '⚙️ الإعدادات والتفضيلات',
              callbackData: 'bot_settings',
            },
            {
              text: '📊 الإحصائيات الحية',
              callbackData: 'bot_stats',
            },
          ],
          [
            {
              text: '🔍 استعلام فوري @smart_helper_bot',
              switchInlineQuery: 'search ',
            },
            {
              text: '🌐 دليل تليجرام للبوتات',
              url: 'https://core.telegram.org/bots/webapps',
            },
          ],
        ],
      },
    },
  ],
  bot_botfather: [
    {
      id: 'msg_bf1',
      chatId: 'bot_botfather',
      senderId: 'BotFather',
      senderName: 'BotFather',
      text: 'I can help you create and manage Telegram bots. If you\'re new to the Bot API, please see the manual: https://core.telegram.org/bots\n\nChoose an action from the options below or send /help for a complete list of commands.',
      timestamp: Date.now() - 1000 * 60 * 120,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [
            { text: '➕ Create New Bot (/newbot)', callbackData: 'bf_newbot' },
            { text: '🤖 My Bots (/mybots)', callbackData: 'bf_mybots' },
          ],
          [
            { text: '📝 Bot Settings', callbackData: 'bf_settings' },
            { text: '🔑 API Tokens', callbackData: 'bf_tokens' },
          ],
        ],
      },
    },
  ],
  bot_wallet: [
    {
      id: 'msg_w1',
      chatId: 'bot_wallet',
      senderId: 'wallet',
      senderName: 'Telegram Wallet',
      text: '💳 **محفظة تليجرام الرسمية**\n\nالرصيد المتاح:\n🔹 **145.50 TON** (~$800.25 USD)\n🔸 **0.015 BTC** (~$1,020.00 USD)\n\nاضغط أدناه لفتح المحفظة التفاعلية أو إجراء عمليات فورية:',
      timestamp: Date.now() - 1000 * 60 * 240,
      isOut: false,
      status: 'read',
      replyMarkup: {
        type: 'inline',
        inlineKeyboard: [
          [
            {
              text: '⚡ فتح المحفظة المصغرة (Wallet App)',
              webApp: { url: 'https://wallet.tg' },
            },
          ],
          [
            { text: '📥 إيداع TON', callbackData: 'wallet_deposit' },
            { text: '📤 إرسال أموال', callbackData: 'wallet_send' },
          ],
          [
            { text: '📜 سجل المعاملات', callbackData: 'wallet_history' },
            { text: '💱 تبادل العملات', callbackData: 'wallet_exchange' },
          ],
        ],
      },
    },
  ],
  channel_telegram_tips: [
    {
      id: 'msg_tip1',
      chatId: 'channel_telegram_tips',
      senderId: 'telegram_tips_ar',
      senderName: 'نصائح تليجرام',
      text: '💡 نصيحة اليوم:\nيمكنك تثبيت المحادثات المهمة في الأعلى بالضغط المطول واختيار "تثبيت" (Pin) لسهولة الوصول إليها دائماً.',
      timestamp: Date.now() - 1000 * 60 * 360,
      isOut: false,
      status: 'read',
      reactions: [{ emoji: '💡', count: 32, userReacted: true }],
    },
  ],
};
