/**
 * Auto-generated by generate_settings_search.cjs
 * Do not edit manually.
 */

export interface SettingsSearchEntry {
  id: string;
  title: string;
  section: string;
  url: string;
}

export const SETTINGS_SEARCH_SECTIONS = [
  "General",
  "Privacy",
  "Notifications",
  "Data",
  "Chat",
  "Language",
  "Folders",
  "Devices",
  "Stories"
] as const;

export const SETTINGS_SEARCH_ENTRIES: SettingsSearchEntry[] = [
  {
    "id": "general",
    "title": "General Settings",
    "section": "General",
    "url": "/settings/general"
  },
  {
    "id": "privacy",
    "title": "Privacy and Security",
    "section": "Privacy",
    "url": "/settings/privacy"
  },
  {
    "id": "notifications",
    "title": "Notifications and Sounds",
    "section": "Notifications",
    "url": "/settings/notifications"
  },
  {
    "id": "data",
    "title": "Data and Storage",
    "section": "Data",
    "url": "/settings/data"
  },
  {
    "id": "chat",
    "title": "Chat Settings",
    "section": "Chat",
    "url": "/settings/chat"
  },
  {
    "id": "language",
    "title": "Language",
    "section": "Language",
    "url": "/settings/language"
  },
  {
    "id": "folders",
    "title": "Chat Folders",
    "section": "Folders",
    "url": "/settings/folders"
  },
  {
    "id": "devices",
    "title": "Devices",
    "section": "Devices",
    "url": "/settings/devices"
  },
  {
    "id": "stories",
    "title": "Stories",
    "section": "Stories",
    "url": "/settings/stories"
  }
];
